### ISSUE TITLE
Running API locally

### ISSUE THREAD

**Issue by wd021** [iron-fish/ironfish-api#867]
I've got the api working fine and am running a node locally. is there anything to help with populating the postgres db from ironfish node db?

**Comment by rohanjadvani** [comment]
You can run [this](https://github.com/iron-fish/ironfish/blob/master/ironfish-cli/src/commands/service/sync.ts) CLI command:
```sh
ironfish service:sync
```

Ensure you set `IRONFISH_API_HOST` and `IRONFISH_API_TOKEN` in your environment to point to your local API server.

**Comment by wd021** [comment]
@rohanjadvani sweet thanks
